#1.What is the total revenue generated by ecommerce_sales during the period covered by this dataset?
SELECT SUM(Total_Amount) AS total_revenue
FROM sales;

#2. How many orders did we receive during the period?
SELECT COUNT(Order_ID) AS total_orders
FROM sales;

#3. How many unique customers have purchased?
SELECT COUNT(DISTINCT Customer_ID) AS unique_customers
FROM customers;

#4.How many units of products have we sold in total?
SELECT pr.Product_ID, Product_Name, sal.Quantity
FROM products AS pr
INNER JOIN sales AS sal
ON pr.Product_ID = sal.Product_ID
ORDER BY pr.Product_ID;

#5.Please provide total revenue generated by each product category.
SELECT DISTINCT Category, SUM(Total_Amount) AS total_revenue
FROM products AS pr
INNER JOIN sales AS sal
ON pr.Product_id = sal.Product_id
GROUP BY Category;

#6.Which product categories received the highest number of orders?
SELECT Category, COUNT(Order_ID) AS highest_orders_no
FROM products AS pr
INNER JOIN sales AS sal
ON pr.Product_ID = sal.Product_ID
GROUP BY Category
ORDER BY highest_orders_no DESC;

#7.Management wants to understand which customer cities generate the most revenue. Provide revenue by city.
SELECT City, SUM(Total_Amount) AS highest_revenue
FROM sales
GROUP BY City
ORDER BY highest_revenue DESC;

#8.Identify all orders where the order value was greater than ₹10,000.
SELECT Order_ID, Customer_ID, Product_ID, Order_Value
FROM sales
WHERE Order_Value > 10000;

#9.Identify customers who generated more than ₹50,000 in total revenue.
SELECT Customer_ID, SUM(Total_Amount) AS total_revenue
FROM sales
GROUP BY Customer_ID
HAVING total_revenue > 50000;

#10.Please identify the 10 products that generated the highest revenue.
WITH profitable_products AS
(
	SELECT Product_Name, MAX(Total_Amount) AS highest_revenue
    FROM products AS pr
    INNER JOIN sales AS sal
    ON pr.Product_ID = sal.Product_ID
    GROUP BY Product_Name
)
SELECT Product_Name, highest_revenue,
ROW_NUMBER() OVER(ORDER BY highest_revenue DESC) AS ranks
FROM profitable_products
LIMIT 10;

#11.Which 10 products generated the lowest revenue?
WITH nprofitable_products AS
(
	SELECT Product_Name, MIN(Total_Amount) AS lowest_revenue
    FROM products AS pr
    INNER JOIN sales AS sal
    ON pr.Product_ID = sal.Product_ID
    GROUP BY Product_Name
)
SELECT Product_Name, lowest_revenue,
ROW_NUMBER() OVER(ORDER BY lowest_revenue ASC) AS ranks
FROM nprofitable_products
LIMIT 10;

#12.Identify our top 10 customers based on total revenue generated.
WITH top_customers AS
(
	SELECT Customer_Name, SUM(Total_Amount) AS total_revenue
    FROM customers AS cust
    INNER JOIN sales AS sal
    ON cust.Customer_ID = sal.Customer_ID
    GROUP BY Customer_Name
)
SELECT Customer_Name, total_revenue,
ROW_NUMBER() OVER(ORDER BY total_revenue DESC) AS ranks
FROM top_customers;

#13.How many customers placed exactly one order during the entire period?
SELECT Customer_ID, COUNT(Order_ID) AS total_orders
FROM sales
GROUP BY Customer_ID
HAVING total_orders = 1;

#14.How many customers placed more than one order?
SELECT COUNT(*) AS repeat_customers
FROM
(
	SELECT Customer_ID
    FROM sales
    GROUP BY Customer_ID
    HAVING COUNT(DISTINCT Order_ID) > 1
) AS highest_cust_orders
;

#15.Provide each customer's total number of orders and total revenue so that the marketing team can identify 
#highly engaged customers.
SELECT cust.Customer_ID, Customer_Name, COUNT(Order_ID) AS total_orders, SUM(Total_Amount) AS total_revenue
FROM customers AS cust
INNER JOIN sales AS sal
ON cust.Customer_ID = sal.Customer_ID
GROUP BY Customer_ID, Customer_Name
ORDER BY total_revenue DESC; 

#Using Window Function
WITH high_cust AS
(
	SELECT cust.Customer_ID, Customer_Name, 
    COUNT(Order_ID) AS total_orders, SUM(Total_Amount) AS total_revenue
    FROM customers AS cust
    INNER JOIN sales AS sal
    ON cust.Customer_ID = sal.Customer_ID
    GROUP BY Customer_ID, Customer_Name
)
SELECT Customer_ID, Customer_Name, total_orders, total_revenue,
ROW_NUMBER() OVER(ORDER BY total_revenue DESC) AS ranks
FROM high_cust;

#16.Identify products whose total revenue is higher than the average revenue generated across all products.
SELECT pr.Product_ID, Product_Name, SUM(Total_Amount) AS total_revenue
FROM products AS pr
INNER JOIN sales AS sal
ON pr.Product_ID = sal.Product_ID
GROUP BY Product_ID, Product_Name
HAVING SUM(Total_Amount) >
(
	SELECT AVG(product_revenue)
    FROM
    (
		SELECT Product_ID, SUM(Total_Amount) AS product_revenue
        FROM sales
        GROUP BY Product_ID
    ) AS product_sales
) ORDER BY total_revenue DESC;

#17.Find customers whose total spending is higher than the average spending of all customers.
SELECT cust.Customer_ID, Customer_Name,
SUM(Total_Amount + Shipping_Cost - Coupon_Discount) AS total_spending
FROM customers AS cust
INNER JOIN sales AS sal
ON cust.Customer_ID = sal.Customer_ID
GROUP BY Customer_ID, Customer_Name
HAVING SUM(Total_Amount + Shipping_Cost - Coupon_Discount) >
(
	SELECT AVG(cust_spending)
    FROM
    (
		SELECT Customer_ID, SUM(Total_Amount + Shipping_Cost - Coupon_Discount) AS cust_spending
        FROM sales
        GROUP BY Customer_ID
    ) AS customer_spent
)
ORDER BY total_spending DESC;

#18.Identify products whose total calculated revenue is higher than the average revenue across all products.
SELECT pr.Product_ID, Product_Name, SUM(sal.Quantity * sal.Unit_Price) AS calculated_revenue
FROM products AS pr
INNER JOIN sales AS sal
ON pr.Product_ID = sal.Product_ID
GROUP BY Product_ID, Product_Name
HAVING SUM(Quantity * Unit_Price) >
(
	SELECT AVG(revenue)
    FROM
    (
		SELECT Product_ID, SUM(Quantity * Unit_Price) AS revenue
        FROM sales
        GROUP BY Product_ID
    ) AS prod_total_revenue
)
ORDER BY calculated_revenue DESC;

#19.Identify categories whose total profit is higher than the average profit across all categories.
SELECT Category, Selling_Price, Original_Price, Quantity,
SUM((Selling_Price - Original_Price) * Quantity) AS total_profit
FROM products AS pr
INNER JOIN sales AS sal
ON pr.Product_ID = sal.Product_ID
GROUP BY Category, Selling_Price, Original_Price, Quantity
HAVING SUM((Selling_Price - Original_Price) * Quantity) >
(
	SELECT AVG(profit)
    FROM 
    (
		SELECT Category, SUM((Selling_Price - Original_Price) * Quantity) AS profit
        FROM products AS pr
        INNER JOIN sales as sal
        ON pr.Product_ID = sal.Product_ID
        GROUP BY Category
    ) AS calculated_profit
)
ORDER BY total_profit;

#20.Find cities whose total sales are greater than the average sales of all cities.
SELECT City, State, SUM(Total_Amount) AS total_sales
FROM sales
GROUP BY City, State
HAVING total_sales >
(
	SELECT AVG(avg_amount)
    FROM
    (
		SELECT City, State, SUM(Total_Amount) AS avg_amount
        FROM sales
        GROUP BY City, State
    ) AS city_sales
)
ORDER BY SUM(Total_Amount) DESC;

#21.Rank customers based on their total revenue, from highest to lowest.
WITH cust_revenue AS
(
	SELECT Customer_Name, SUM(Total_Amount) AS total_revenue
    FROM customers AS cust
    INNER JOIN sales AS sal
    ON cust.Customer_ID = sal.Customer_ID
    GROUP BY Customer_Name
)
SELECT Customer_Name, total_revenue,
ROW_NUMBER() OVER(ORDER BY total_revenue DESC) AS ranks
FROM cust_revenue;

#22.Show the customer's total revenue for each month.
SELECT YEAR(Order_Date) AS years, MONTH(Order_Date) AS months, SUM(Quantity * Unit_Price) AS total_revenue
FROM sales
GROUP BY years, months
ORDER BY total_revenue;

#23.Show the number of orders received each month.
SELECT MONTH(Order_date) AS months, COUNT(Order_ID) AS no_of_orders
FROM sales
GROUP BY months
ORDER BY no_of_orders DESC;

#24.How revenue changed compared with the previous month.
WITH prev_month AS
(
	SELECT SUM(Quantity * Unit_Price) AS total_revenue, YEAR(Order_Date) AS years,
    MONTH(Order_Date) AS months
    FROM products AS pr
    INNER JOIN sales AS sal
    ON pr.Product_ID = sal.Product_ID
    GROUP BY years, months
),
revenue_compare AS
(
	SELECT years, months, total_revenue,
    LAG(total_revenue) OVER(ORDER BY years, months) AS prev_month_revenue
    FROM prev_month
)
SELECT total_revenue, years, months, prev_month_revenue,
ROUND((total_revenue - prev_month_revenue) / prev_month_revenue * 100, 2) AS growth_percentage
FROM revenue_compare
ORDER BY years, months;

#25.Show the revenue generated by each product category along with the number of unique customers 
#purchasing from that category.
WITH cust_category AS
(
	SELECT pr.Category, COUNT(DISTINCT Customer_ID) AS unique_customers, 
    SUM(Quantity * Unit_Price) AS total_revenue
	FROM sales AS sal
    INNER JOIN products AS pr
    ON sal.Product_ID = pr.Product_ID
	GROUP BY Category
    ORDER BY total_revenue
)
SELECT *
FROM cust_category
ORDER BY total_revenue DESC;